name: ci-cd

on:
  push:
    branches:
      - master

env:
  PRODUCTION: true
  HUGO_VERSION: '0.66.0'
  NODE_VERSION: '12.16.1'
  NETLIFY_SITE_ID: 'e57c3b42-5d4c-40e0-99c8-1b5057d80680'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_KINKPROFILE }}

jobs:
  build-and-deploy:
    name: Build & deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci
        npm i -g postcss-cli autoprefixer
      if: success()
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
      if: success()
    - name: Build site
      run: hugo
      if: success()
    - name: Deploy site
      uses: netlify/actions/cli@master
      with:
        args: "deploy --prod --dir public"
      if: success()
