name: ci-cd

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '12.16.1'
  NETLIFY_SITE_ID: 'e57c3b42-5d4c-40e0-99c8-1b5057d80680'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_KINKPROFILE }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Deploy site
      uses: netlify/actions/cli@master
      with:
        args: "deploy --prod"
      if: success()
